# -*- coding: utf-8 -*-
"""5 june.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UzkC6OUC1FJOOzHGTnRfffLuJmvREIta
"""

#data type
age=18
print(id(age))

salary=age
print(id(salary))
salary=20
print("newid",id(salary))

x="rajasthan"
print(x)

x="rajasthan"
print(x[4])

x="rajasthan"
print(x[-2])

#slicing[sart: stop:[step=1]]
x="rajasthan"
print(x[2:4])

x="rajasthan"
print(x[0:])

x="rajasthan"
print(x[:5])

x="rajasthan"
print(x[0:6])

x="rajasthan"
print(x[0:])

x="rajasthan"
print(x[0:4:2])

x="rajasthan"
print(x[2:6:2])

x="rajasthan"
print(x[2::2])

x="rajasthan"
print(x[0:4:-1])

x="rajasthan"
print(x[-1:-3:-1])

x="rajasthan"
print(x[-4:-1:-1])

x="rajasthan"
print(x[-4:-1:1])

#conditinal statement
print("hello")

#if conditinal statement
'''
if(conditinal):
    print(" ")
    '''

age=19
if(age==18):
  print("he can vote")
else:
    print("he can not vote")

age=18
country="india"
if(age==18 and country=="india"):
  print("he can vote")
else:
    print("he can not vote")

country="india"
if(age>=18):
    print("voter id +adhar card")
elif(country=="india"):
    print("adhar card")
else:
    print("no adhar ")

a=20
if(a%2==0):
    print("even num")
else:
    print("odd num")

a=input("enter a number :")
b=input("enter b number :")
c=input("enter c number :")
if(a>b and c<a):
    print("a is meximum")
elif(b>c and a>c ):
    print("b is meximum")
else:
    print("c is meximum")

6
50
40
marks=int(input("enter a marks :"))
if(marks>=60 and marks<70):
    print("average")
elif(marks>=70 and marks<80):
    print("good")
elif(marks>=81 and marks<90):
    print("very good")
elif(marks>=90):
    print("excellent")
else:
    print("fail")

a = int(input("Enter a number: "))
b = int(input("Enter b number: "))
c = int(input("Enter c number: "))

if a < b and a < c:
    print("a is minimum")
elif b < a and b < c:
    print("b is minimum")
else:
    print("c is minimum")

a=int(input("enter a weeks days :"))
if(a==1):
    print("sun")
elif(a==2):
    print("mon")
elif(a==3):
    print("tue")
elif(a==4):
    print("wed")
elif(a==5):
    print("thu")
elif(a==6):
    print("fri")
elif(a==7):
    print("sat")
else:
    print("error")

a=int(input("enter a months :"))
if(a==1):
   print("dec")
elif(a==2):
    print("nov")
elif(a==3):
    print("oct")
elif(a==4):
    print("sept")
elif(a==5):
    print("aug")
elif(a==6):
    print("july")
elif(a==7):
    print("june")
elif(a==8):
    print("may")
elif(a==9):
    print("april")
elif(a==10):
    print("march")
elif(a==11):
    print("feb")
elif(a==12):
    print("jan")
else:
    print("error")

