# -*- coding: utf-8 -*-
"""8may.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVl63yz11bu4mTWhcHxRgu-o7mPsSzhe
"""

#data type
x=10
print(x ,id(x))
y=x
print("y :",id(y))

y=15
print(id(y),id(x))

10/2

20//5

20%6

x=5
x*=5
print(x)

14&13

13&12

14|13

11>>1

13>>5

13>>3

23>>1

23>>4

24>>1

14<<2

15<<3

"j" in "jaipur"

"J" in "jaipur"

"purr"not in "jaipur"

"pur"not in "jaipur"

x=10
type(x)is int



