# -*- coding: utf-8 -*-
"""assignment 22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16N0qf3e7OOfDw0RDW-FF-UiQtwVClIpK
"""

a = input("enter the string :")
valid_parentheses = ["{}[]", "()", "[]", "{}"]  # Define valid strings
if a in valid_parentheses:  # Check if input is in the list of valid strings
    print("valid")
else:
    print("invalid")

x="regex softwere"
for i in x.split():
        print(i[0:-1]+i[-1].upper(),end=" ")

