# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rX1wncoMz8BzSkZBIYwhLVXysjWukeM7
"""

#nasted if-else
a=12
if(a%2==0):
    print("divisible by 2")
    if(a%3==0):
        print("divisible by 6")
    else:
        print("no ")
else:
      print("no divisible")

10/2

for x in range(1,8):
  if(x%2==0):
    print("even num")
    print(x)

total=0
for i in range(1,6):
    total+=x
    print(total)

total=0
for i in range(100,1,-1):
    if(i%7==0):
      total +=i
print(total)

for i in range(100, 1, -1):
    if (i%7==0):
     print(i)

#string
for x in "hello":
    print(x)

data="regex"
for char in data:
    print(char,end=" ")

data="regex"
for char in data:
    print(len(data))

data="jaipur"
for i in  range(0,6):
    print(data[i])

data="jaipur"
#range(0,8)
for i in  range(0,len(data)):
    print(data[i])

vowels="aeiou"
for i in range(0,len(data)):
    print(data[i])

data="jaipur"
for char in data:
    if char in range(0,len(data)):
       print(char)

for i in "jaipur":
    if i in "aeiou":
        print("vowels:", i)

